#!/usr/bin/env groovy

def sendFailureEmail() {
    def content = "Build for branch ${env.BRANCH_NAME} Failed."
    def info = 'Check the attached log or log into jenkins'
    emailext(
        mimeType: "text/html; charset=UTF-8",
        to: "josegar0218@gmail.com",
        recipientProviders: [[$class: 'CulpritsRecipientProvider'], [$class: "RequesterRecipientProvider"]],
        body: "${content}<br/>${info}<br/>",
        subject: "Jenkins: Your build ${env.BRANCH_NAME} - Build #${env.BUILD_NUMBER} - Failed!",
        attachLog: true,
        attachmentsPattern: 'reports.zip'
    )
}

node() {
    try{
        stage("Setup"){
            checkout scm
        }
        dir("springboot"){
        stage("Test") {
            withMaven(maven: 'maven', jdk: 'jdk') {
                sh("mvn clean test -U")
            }
        }
        stage("Build JAR artifact") {
            withMaven(maven: 'maven', jdk: 'jdk') {
                sh(" mvn clean package")
            }
        }
        stage("Build Docker image"){
            dockerImage = docker.build("382356559478.dkr.ecr.us-east-1.amazonaws.com/jsgd/demoback")
        }
        stage("Push Docker image"){
            docker.withRegistry('https://382356559478.dkr.ecr.us-east-1.amazonaws.com/jsgd/demoback','ecr:us-east-1'){
                dockerImage.push();
                dockerImage.push('latest')
            }


        }
    }
    } catch(error) {
        throw error
		sendFailureEmail()
    } finally {
        cleanWs()
    }
}