apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
      - name: {{ .Values.name}}
        image: {{ .Values.image}}
        ports:
        - containerPort: {{ .Values.port}}
        readinessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.port}}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.port}}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
spec:
  type: {{ .Values.servicetype}}
  ports:
  - port: {{ .Values.port}}
    targetPort: {{ .Values.port}}
    protocol: TCP
  selector:
    app: {{ .Values.name}}